"""Initial tables

Revision ID: 83bd1ae25c66
Revises: 
Create Date: 2025-07-07 22:00:20.392519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '83bd1ae25c66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='사용자 이메일'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='사용자 닉네임'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='해시된 비밀번호'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='관리자 여부'),
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='기본키'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('curriculums',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='사용자 ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='커리큘럼 제목'),
    sa.Column('goal', sa.String(length=255), nullable=False, comment='학습 목표'),
    sa.Column('duration_weeks', sa.Integer(), nullable=False, comment='커리큘럼 주차'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='공개 상태'),
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='기본키'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_curriculums_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculums'))
    )
    op.create_index(op.f('ix_curriculums_is_public'), 'curriculums', ['is_public'], unique=False)
    op.create_table('week_topics',
    sa.Column('curriculum_id', sa.String(length=36), nullable=False, comment='커리큘럼 ID'),
    sa.Column('week_number', sa.Integer(), nullable=False, comment='학습 주차'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='주차 별 제목'),
    sa.Column('description', sa.Text(), nullable=True, comment='주차 별 설명'),
    sa.Column('learning_goals', sa.JSON(), nullable=False, comment='학습 내용'),
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='기본키'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculums.id'], name=op.f('fk_week_topics_curriculum_id_curriculums')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_week_topics'))
    )
    op.create_table('summaries',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='사용자 ID'),
    sa.Column('week_topic_id', sa.String(length=36), nullable=False, comment='주차별 ID'),
    sa.Column('content', sa.Text(), nullable=True, comment='주차 별 요약본'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='공개 상태'),
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='기본키'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_summaries_user_id_users')),
    sa.ForeignKeyConstraint(['week_topic_id'], ['week_topics.id'], name=op.f('fk_summaries_week_topic_id_week_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_summaries'))
    )
    op.create_index(op.f('ix_summaries_is_public'), 'summaries', ['is_public'], unique=False)
    op.create_table('feedbacks',
    sa.Column('summary_id', sa.String(length=36), nullable=False, comment='주차별 피드백'),
    sa.Column('content', sa.Text(), nullable=False, comment='피드백 내용'),
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='기본키'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.id'], name=op.f('fk_feedbacks_summary_id_summaries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedbacks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_summaries_is_public'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_table('week_topics')
    op.drop_index(op.f('ix_curriculums_is_public'), table_name='curriculums')
    op.drop_table('curriculums')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
