import user.infra.db_models.user  # type: ignore  # noqa: F401
import curriculum.infra.db_models.curriculum  # type: ignore  # noqa: F401
import curriculum.infra.db_models.week_schedule  # type: ignore  # noqa: F401
import curriculum.infra.db_models.summary  # type: ignore  # noqa: F401
import curriculum.infra.db_models.feedback  # type: ignore  # noqa: F401
import curriculum.infra.db_models.like  # type: ignore  # noqa: F401
import curriculum.infra.db_models.bookmark  # type: ignore  # noqa: F401
import curriculum.infra.db_models.comment  # type: ignore  # noqa: F401
import curriculum.infra.db_models.tag  # type: ignore  # noqa: F401
import curriculum.infra.db_models.category  # type: ignore  # noqa: F401
import curriculum.infra.db_models.curriculum_tag  # type: ignore  # noqa: F401
